name: Increment Click Count

on:
  workflow_dispatch: # Manual trigger or you can set other events

jobs:
  increment_count:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Increment Script
      run: |
        python increment_click_count.py
